### ISSUE TITLE
java.lang.VerifyError: Expecting a stackmap frame at branch target 56

### ISSUE THREAD

**Issue by eschava** [toddlipcon/jcarder#6]
Happens at lockclasses-new branch. I had to enable "-noverify" option to work around this issue

java.lang.VerifyError: Expecting a stackmap frame at branch target 56
Exception Details:
  Location:
    com/enea/jcarder/agent/JavaAgent.handleOutputDirProperty()V @45: ifne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 121c 1301 5cb8 0146 4c2b 1301 5eb8 0162
    0x0000010: b801 66b6 016a 4c2a bb00 8159 2bb7 016c
    0x0000020: b601 70b5 0062 2ab4 0062 b601 739a 000b
    0x0000030: 2ab4 0062 b601 7657 b1                 

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:327)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Exception in thread "main" FATAL ERROR in native method: processing of -javaagent failed

**Comment by toddlipcon** [comment]
Can you try this branch? https://github.com/toddlipcon/jcarder/tree/lockclasses-new

**Comment by eschava** [comment]
I'm talking about exactly same branch

**Comment by eschava** [comment]
Looks like the issue could be resolved with upgrading jarjar library to the latest 1.4 version
